services:
  - type: web
    name: ash-instagram-downloader-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 main.py
    plan: free
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_IDS
        value: "8378171861,8192070400"
      - key: FORCE_SUB_CHANNEL
        value: "MoviesGroupG3"
      - key: LOG_CHANNEL_ID
        value: "-1004350432978"
      - key: BOT_NAME
        value: "Ash Insta Downloader Bot"
      - key: PORT
        value: "8080"
